package br.com.devsuperior.dev_xp_ai;

import jakarta.annotation.PostConstruct;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.net.URI;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

@RestController
@RequestMapping("/developers")
public class DevController {

    private static final Pattern SIMPLE_EMAIL_PATTERN = Pattern.compile("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$");
    private static final Pattern NICKNAME_PATTERN = Pattern.compile("^[a-zA-Z0-9._-]{3,30}$");
    private static final Set<String> VALID_UFS = Set.of(
            "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT",
            "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO",
            "RR", "SC", "SP", "SE", "TO"
    );

    private final JdbcTemplate jdbcTemplate;

    public DevController(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @PostConstruct
    void createTableIfNeeded() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS tb_developer (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    full_name VARCHAR(120) NOT NULL,
                    email VARCHAR(120) NOT NULL UNIQUE,
                    nickname VARCHAR(30) NOT NULL UNIQUE,
                    uf VARCHAR(2) NOT NULL,
                    years_of_experience INT NOT NULL,
                    primary_language VARCHAR(50) NOT NULL,
                    interested_in_ai BOOLEAN NOT NULL,
                    skills VARCHAR(300) NOT NULL
                )
                """);
    }

    @PostMapping
    public ResponseEntity<?> createDeveloper(
            @RequestHeader("correlationId") UUID correlationId,
            @RequestBody DeveloperRequest request
    ) {
        List<String> validationErrors = validateCreateRequest(request);
        if (!validationErrors.isEmpty()) {
            return badRequest("Falha de validacao", validationErrors);
        }

        String normalizedEmail = request.email().trim().toLowerCase(Locale.ROOT);
        String normalizedNickname = normalizeNickname(request.nickname());
        String normalizedUf = request.uf().trim().toUpperCase(Locale.ROOT);
        String normalizedLanguage = normalizeTitleCase(request.primaryLanguage());
        String normalizedName = normalizeTitleCase(request.fullName());
        List<String> normalizedSkillsList = normalizeSkills(request.skills());
        String normalizedSkills = serializeSkills(normalizedSkillsList);

        if (existsByEmail(normalizedEmail)) {
            return conflict("Email ja cadastrado", List.of("Ja existe um desenvolvedor com este email."));
        }

        if (existsByNickname(normalizedNickname)) {
            return conflict("Nickname ja cadastrado", List.of("Ja existe um desenvolvedor com este nickname."));
        }

        Long generatedId = insertDeveloper(
                normalizedName,
                normalizedEmail,
                normalizedNickname,
                normalizedUf,
                request.yearsOfExperience(),
                normalizedLanguage,
                request.interestedInAi(),
                normalizedSkills
        );

        DeveloperResponse response = new DeveloperResponse(
                generatedId,
                normalizedName,
                normalizedEmail,
                normalizedNickname,
                normalizedUf,
                request.yearsOfExperience(),
                normalizedLanguage,
                request.interestedInAi(),
                normalizedSkillsList
        );

        return ResponseEntity.created(URI.create("/developers/" + generatedId)).body(response);
    }

    @GetMapping
    public ResponseEntity<?> listDevelopers(
            @RequestHeader("correlationId") UUID correlationId,
            @RequestParam(required = false) String uf,
            @RequestParam(required = false) String language
    ) {
        StringBuilder sql = new StringBuilder("""
                SELECT id, full_name, email, nickname, uf, years_of_experience, primary_language, interested_in_ai, skills
                FROM tb_developer
                WHERE 1 = 1
                """);
        List<Object> params = new ArrayList<>();

        if (hasText(uf)) {
            String normalizedUf = uf.trim().toUpperCase(Locale.ROOT);
            if (!VALID_UFS.contains(normalizedUf)) {
                return badRequest("Filtro invalido", List.of("O filtro UF deve ser uma sigla de estado brasileira valida."));
            }
            sql.append(" AND uf = ?");
            params.add(normalizedUf);
        }

        if (hasText(language)) {
            sql.append(" AND LOWER(primary_language) = LOWER(?)");
            params.add(language.trim());
        }

        sql.append(" ORDER BY id");

        List<DeveloperResponse> developers = jdbcTemplate.query(
                sql.toString(),
                developerRowMapper(),
                params.toArray()
        );
        return ResponseEntity.ok(developers);
    }

    @GetMapping("/{id}")
    public ResponseEntity<?> getDeveloperById(
            @RequestHeader("correlationId") UUID correlationId,
            @PathVariable Long id
    ) {
        try {
            DeveloperResponse response = loadDeveloperById(id);
            return ResponseEntity.ok(response);
        } catch (EmptyResultDataAccessException ex) {
            return notFound("Desenvolvedor nao encontrado", List.of("Nao existe desenvolvedor com id " + id + "."));
        }
    }

    @PutMapping("/{id}/experience")
    public ResponseEntity<?> updateExperience(
            @RequestHeader("correlationId") UUID correlationId,
            @PathVariable Long id,
            @RequestBody UpdateExperienceRequest request
    ) {
        List<String> validationErrors = validateExperienceUpdate(request);
        if (!validationErrors.isEmpty()) {
            return badRequest("Falha de validacao", validationErrors);
        }

        int rowsUpdated = jdbcTemplate.update(
                "UPDATE tb_developer SET years_of_experience = ? WHERE id = ?",
                request.yearsOfExperience(),
                id
        );

        if (rowsUpdated == 0) {
            return notFound("Desenvolvedor nao encontrado", List.of("Nao existe desenvolvedor com id " + id + "."));
        }

        DeveloperResponse response = loadDeveloperById(id);
        return ResponseEntity.ok(response);
    }

    private DeveloperResponse loadDeveloperById(Long id) {
        return jdbcTemplate.queryForObject(
                """
                SELECT id, full_name, email, nickname, uf, years_of_experience, primary_language, interested_in_ai, skills
                FROM tb_developer
                WHERE id = ?
                """,
                developerRowMapper(),
                id
        );
    }

    private RowMapper<DeveloperResponse> developerRowMapper() {
        return (rs, rowNum) -> new DeveloperResponse(
                rs.getLong("id"),
                rs.getString("full_name"),
                rs.getString("email"),
                rs.getString("nickname"),
                rs.getString("uf"),
                rs.getInt("years_of_experience"),
                rs.getString("primary_language"),
                rs.getBoolean("interested_in_ai"),
                deserializeSkills(rs.getString("skills"))
        );
    }

    private Long insertDeveloper(
            String fullName,
            String email,
            String nickname,
            String uf,
            Integer yearsOfExperience,
            String primaryLanguage,
            Boolean interestedInAi,
            String skillsCsv
    ) {
        KeyHolder keyHolder = new GeneratedKeyHolder();
        jdbcTemplate.update(connection -> {
            PreparedStatement ps = connection.prepareStatement(
                    """
                    INSERT INTO tb_developer
                        (full_name, email, nickname, uf, years_of_experience, primary_language, interested_in_ai, skills)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    Statement.RETURN_GENERATED_KEYS
            );
            ps.setString(1, fullName);
            ps.setString(2, email);
            ps.setString(3, nickname);
            ps.setString(4, uf);
            ps.setInt(5, yearsOfExperience);
            ps.setString(6, primaryLanguage);
            ps.setBoolean(7, interestedInAi);
            ps.setString(8, skillsCsv);
            return ps;
        }, keyHolder);

        return extractGeneratedId(keyHolder);
    }

    private Long extractGeneratedId(KeyHolder keyHolder) {
        if (keyHolder.getKey() != null) {
            return keyHolder.getKey().longValue();
        }
        Map<String, Object> keyMap = keyHolder.getKeys();
        if (keyMap != null && keyMap.containsKey("ID")) {
            return ((Number) keyMap.get("ID")).longValue();
        }
        if (keyMap != null && keyMap.containsKey("id")) {
            return ((Number) keyMap.get("id")).longValue();
        }
        throw new IllegalStateException("Nao foi possivel ler o id gerado apos o insert.");
    }

    private boolean existsByEmail(String email) {
        Integer total = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM tb_developer WHERE LOWER(email) = LOWER(?)",
                Integer.class,
                email
        );
        return total != null && total > 0;
    }

    private boolean existsByNickname(String nickname) {
        Integer total = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM tb_developer WHERE LOWER(nickname) = LOWER(?)",
                Integer.class,
                nickname
        );
        return total != null && total > 0;
    }

    private List<String> validateCreateRequest(DeveloperRequest request) {
        List<String> errors = new ArrayList<>();
        if (request == null) {
            errors.add("O corpo da requisicao e obrigatorio.");
            return errors;
        }
        if (!hasText(request.fullName()) || request.fullName().trim().length() < 5 || request.fullName().trim().length() > 120) {
            errors.add("fullName deve ter entre 5 e 120 caracteres.");
        }
        if (!hasText(request.email()) || !SIMPLE_EMAIL_PATTERN.matcher(request.email().trim()).matches()) {
            errors.add("email deve ter um formato valido.");
        }
        if (!hasText(request.nickname()) || !NICKNAME_PATTERN.matcher(request.nickname().trim()).matches()) {
            errors.add("nickname deve ter de 3 a 30 caracteres e usar apenas letras, numeros, ponto, underscore ou hifen.");
        }
        if (!hasText(request.uf()) || !VALID_UFS.contains(request.uf().trim().toUpperCase(Locale.ROOT))) {
            errors.add("uf deve ser uma sigla de estado brasileira valida.");
        }
        if (request.yearsOfExperience() == null || request.yearsOfExperience() < 0 || request.yearsOfExperience() > 60) {
            errors.add("yearsOfExperience deve estar entre 0 e 60.");
        }
        if (!hasText(request.primaryLanguage()) || request.primaryLanguage().trim().length() > 50) {
            errors.add("primaryLanguage e obrigatorio e deve ter no maximo 50 caracteres.");
        }
        if (request.interestedInAi() == null) {
            errors.add("interestedInAi e obrigatorio.");
        }
        if (request.skills() == null || request.skills().isEmpty()) {
            errors.add("skills deve conter ao menos um item.");
        } else {
            if (request.skills().size() > 10) {
                errors.add("skills pode conter no maximo 10 itens.");
            }
            for (String skill : request.skills()) {
                if (!hasText(skill) || skill.trim().length() < 2 || skill.trim().length() > 30) {
                    errors.add("cada skill deve ter entre 2 e 30 caracteres.");
                    break;
                }
            }
        }
        return errors;
    }

    private List<String> validateExperienceUpdate(UpdateExperienceRequest request) {
        List<String> errors = new ArrayList<>();
        if (request == null || request.yearsOfExperience() == null) {
            errors.add("yearsOfExperience e obrigatorio.");
            return errors;
        }
        if (request.yearsOfExperience() < 0 || request.yearsOfExperience() > 60) {
            errors.add("yearsOfExperience deve estar entre 0 e 60.");
        }
        return errors;
    }

    private ResponseEntity<ErrorResponse> badRequest(String message, List<String> details) {
        return ResponseEntity.badRequest().body(new ErrorResponse(message, details));
    }

    private ResponseEntity<ErrorResponse> conflict(String message, List<String> details) {
        return ResponseEntity.status(HttpStatus.CONFLICT).body(new ErrorResponse(message, details));
    }

    private ResponseEntity<ErrorResponse> notFound(String message, List<String> details) {
        return ResponseEntity.status(HttpStatus.NOT_FOUND).body(new ErrorResponse(message, details));
    }

    private String normalizeNickname(String nickname) {
        return nickname == null ? "" : nickname.trim().toLowerCase(Locale.ROOT);
    }

    private String normalizeTitleCase(String text) {
        if (!hasText(text)) {
            return "";
        }
        String normalizedWhitespace = text.trim().replaceAll("\\s+", " ");
        return Arrays.stream(normalizedWhitespace.split(" "))
                .map(this::capitalizeWord)
                .collect(Collectors.joining(" "));
    }

    private String capitalizeWord(String word) {
        String lower = word.toLowerCase(Locale.ROOT);
        return Character.toUpperCase(lower.charAt(0)) + lower.substring(1);
    }

    private List<String> normalizeSkills(List<String> skills) {
        if (skills == null) {
            return List.of();
        }
        return skills.stream()
                .map(this::normalizeTitleCase)
                .toList();
    }

    private String serializeSkills(List<String> skills) {
        return skills.stream()
                .map(String::trim)
                .collect(Collectors.joining(","));
    }

    private List<String> deserializeSkills(String csv) {
        if (!hasText(csv)) {
            return List.of();
        }
        return Arrays.stream(csv.split(","))
                .map(String::trim)
                .filter(this::hasText)
                .toList();
    }

    private boolean hasText(String value) {
        return value != null && !value.trim().isEmpty();
    }

    public record DeveloperRequest(
            String fullName,
            String email,
            String nickname,
            String uf,
            Integer yearsOfExperience,
            String primaryLanguage,
            Boolean interestedInAi,
            List<String> skills
    ) {
    }

    public record UpdateExperienceRequest(Integer yearsOfExperience) {
    }

    public record DeveloperResponse(
            Long id,
            String fullName,
            String email,
            String nickname,
            String uf,
            Integer yearsOfExperience,
            String primaryLanguage,
            Boolean interestedInAi,
            List<String> skills
    ) {
    }

    public record ErrorResponse(String message, List<String> details) {
    }
}